dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  firefox: latest

language: node_js
node_js:
  - "node"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
script:
  - npm run lint
  - npm run lint:style
  - npm run test
  - npm run test:e2e:chrome:headless
